monolog:
    handlers:
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 10
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #chromeinvoke:
        #    type: chromeinvoke
        #  channels: [!doctrine, !security]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                max_files: 10
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
        handlers_with_fingers_crossed: ~
